package com.reje.pojo;


import javax.validation.constraints.Pattern;

public class Emp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.emp_id
     *
     * @mbggenerated Fri Mar 25 14:42:08 CST 2022
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.emp_name
     *
     * @mbggenerated Fri Mar 25 14:42:08 CST 2022
     */
    @Pattern(regexp="(^[a-zA-Z0-9_-]{6,16}$)|(^[\\u2E80-\\u9FFF]{2,5}$)",message = "用户名必须是2-5位中文或6-16位英文和数字的组合")
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.emp_sex
     *
     * @mbggenerated Fri Mar 25 14:42:08 CST 2022
     */
    private String empSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.emp_email
     *
     * @mbggenerated Fri Mar 25 14:42:08 CST 2022
     */
    @Pattern(regexp = "(^[a-z0-9_\\.-]+)@([\\da-z\\.-]+)\\.([a-z\\.]{2,6}$)"
            ,message = "邮箱格式不正确")
    private String empEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.cid
     *
     * @mbggenerated Fri Mar 25 14:42:08 CST 2022
     */
    private Integer cid;

    private Dept dept;

    public Emp() {
    }

    public Emp(Integer empId, String empName, String empSex, String empEmail, Integer cid) {
        this.empId = empId;
        this.empName = empName;
        this.empSex = empSex;
        this.empEmail = empEmail;
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.emp_id
     *
     * @return the value of emp.emp_id
     *
     * @mbggenerated Fri Mar 25 14:42:08 CST 2022
     */

    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.emp_id
     *
     * @param empId the value for emp.emp_id
     *
     * @mbggenerated Fri Mar 25 14:42:08 CST 2022
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.emp_name
     *
     * @return the value of emp.emp_name
     *
     * @mbggenerated Fri Mar 25 14:42:08 CST 2022
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.emp_name
     *
     * @param empName the value for emp.emp_name
     *
     * @mbggenerated Fri Mar 25 14:42:08 CST 2022
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.emp_sex
     *
     * @return the value of emp.emp_sex
     *
     * @mbggenerated Fri Mar 25 14:42:08 CST 2022
     */
    public String getEmpSex() {
        return empSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.emp_sex
     *
     * @param empSex the value for emp.emp_sex
     *
     * @mbggenerated Fri Mar 25 14:42:08 CST 2022
     */
    public void setEmpSex(String empSex) {
        this.empSex = empSex == null ? null : empSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.emp_email
     *
     * @return the value of emp.emp_email
     *
     * @mbggenerated Fri Mar 25 14:42:08 CST 2022
     */
    public String getEmpEmail() {
        return empEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.emp_email
     *
     * @param empEmail the value for emp.emp_email
     *
     * @mbggenerated Fri Mar 25 14:42:08 CST 2022
     */
    public void setEmpEmail(String empEmail) {
        this.empEmail = empEmail == null ? null : empEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.cid
     *
     * @return the value of emp.cid
     *
     * @mbggenerated Fri Mar 25 14:42:08 CST 2022
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.cid
     *
     * @param cid the value for emp.cid
     *
     * @mbggenerated Fri Mar 25 14:42:08 CST 2022
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    public Dept getDept() {
        return dept;
    }

    public void setDept(Dept dept) {
        this.dept = dept;
    }

    @Override
    public String toString() {
        return "Emp{" +
                "empId=" + empId +
                ", empName='" + empName + '\'' +
                ", empSex='" + empSex + '\'' +
                ", empEmail='" + empEmail + '\'' +
                ", cid=" + cid +
                ", dept=" + dept +
                '}';
    }
}